from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from .etl.load import Load
from .models import Base, Collision, Vehicle, Location, Date  # User, Address, Company


# print('These are your DB Classses===>',Base, User, Address, Company)
print('These are your DB Classses===>',Base, Collision, Vehicle, Location, Date)
print('LIST', Collision.__table__.columns)
print('Your List :',[ column.key for column in Collision.__table__.columns])
app = Flask(__name__)
app.config["SQLALCHEMY_DATABASE_URI"] = "postgresql://localhost/portfolio_db_test_1"
db = SQLAlchemy(model_class=Base)
db.init_app(app)
with app.app_context():
    db.create_all()


j = [
 {'fatalities': 0,
  'serious_injuries': 0,
  'added_date': '2023/06/04 00:00:00+00',
  'modified_date': '2023/10/30 00:00:00+00',
  'incident_date': '5/1/2023 6:58:00 PM',
  'speed': 'Y',
  'light_condition': 'Daylight',
  'weather': 'Raining',
  'road_condition': 'Wet',
  'address': 'SW ADMIRAL WAY BETWEEN ADMIRAL AVALON RP AND SW ADMIRAL WY OFF RP',
  'location_type': 'Block',
  'lon': -122.371755287,
  'lat': 47.5717276930001,
  'pedestrian_cycle_count': 0,
  'injuries': 0,
  'pedestrian_count': 0,
  'vehicle_count': 1,
  'severity': 'Property Damage Only Collision',
  'source': 'Police Traffic Collision Report',
  'collision_type': 'Other',
  'junction_type': 'Mid-Block (not related to intersection)',
  'report_number': '3904353'},
 {'fatalities': 0,
  'serious_injuries': 0,
  'added_date': '2023/06/04 00:00:00+00',
  'modified_date': '2023/10/30 00:00:00+00',
  'incident_date': '5/1/2023 6:58:00 PM',
  'speed': 'Y',
  'light_condition': 'Daylight',
  'weather': 'Raining',
  'road_condition': 'Wet',
  'address': 'SW ADMIRAL WAY BETWEEN ADMIRAL AVALON RP AND SW ADMIRAL WY OFF RP',
  'location_type': 'Block',
  'lon': -122.371755287,
  'lat': 47.5717276930001,
  'pedestrian_cycle_count': 0,
  'injuries': 0,
  'pedestrian_count': 0,
  'vehicle_count': 1,
  'severity': 'Property Damage Only Collision',
  'source': 'Police Traffic Collision Report',
  'collision_type': 'Other',
  'junction_type': 'Mid-Block (not related to intersection)',
  'report_number': '3904353'},
 {'fatalities': 0,
  'serious_injuries': 0,
  'added_date': '2023/06/04 00:00:00+00',
  'modified_date': '2023/10/30 00:00:00+00',
  'incident_date': '5/1/2023 6:58:00 PM',
  'speed': 'Y',
  'light_condition': 'Daylight',
  'weather': 'Raining',
  'road_condition': 'Wet',
  'address': 'SW ADMIRAL WAY BETWEEN ADMIRAL AVALON RP AND SW ADMIRAL WY OFF RP',
  'location_type': 'Block',
  'lon': -122.371755287,
  'lat': 47.5717276930001,
  'pedestrian_cycle_count': 0,
  'injuries': 0,
  'pedestrian_count': 0,
  'vehicle_count': 1,
  'severity': 'Property Damage Only Collision',
  'source': 'Police Traffic Collision Report',
  'collision_type': 'Other',
  'junction_type': 'Mid-Block (not related to intersection)',
  'report_number': '3904353'},
 {'fatalities': 0,
  'serious_injuries': 0,
  'added_date': '2023/06/04 00:00:00+00',
  'modified_date': '2023/10/30 00:00:00+00',
  'incident_date': '5/1/2023 6:58:00 PM',
  'speed': 'Y',
  'light_condition': 'Daylight',
  'weather': 'Raining',
  'road_condition': 'Wet',
  'address': 'SW ADMIRAL WAY BETWEEN ADMIRAL AVALON RP AND SW ADMIRAL WY OFF RP',
  'location_type': 'Block',
  'lon': -122.371755287,
  'lat': 47.5717276930001,
  'pedestrian_cycle_count': 0,
  'injuries': 0,
  'pedestrian_count': 0,
  'vehicle_count': 1,
  'severity': 'Property Damage Only Collision',
  'source': 'Police Traffic Collision Report',
  'collision_type': 'Other',
  'junction_type': 'Mid-Block (not related to intersection)',
  'report_number': '3904353'},
 {'fatalities': 0,
  'serious_injuries': 0,
  'added_date': '2023/06/04 00:00:00+00',
  'modified_date': '2023/10/30 00:00:00+00',
  'incident_date': '5/1/2023 6:58:00 PM',
  'speed': 'Y',
  'light_condition': 'Daylight',
  'weather': 'Raining',
  'road_condition': 'Wet',
  'address': 'SW ADMIRAL WAY BETWEEN ADMIRAL AVALON RP AND SW ADMIRAL WY OFF RP',
  'location_type': 'Block',
  'lon': -122.371755287,
  'lat': 47.5717276930001,
  'pedestrian_cycle_count': 0,
  'injuries': 0,
  'pedestrian_count': 0,
  'vehicle_count': 1,
  'severity': 'Property Damage Only Collision',
  'source': 'Police Traffic Collision Report',
  'collision_type': 'Other',
  'junction_type': 'Mid-Block (not related to intersection)',
  'report_number': '3904353'},
 {'fatalities': 0,
  'serious_injuries': 0,
  'added_date': '2023/06/04 00:00:00+00',
  'modified_date': '2023/10/30 00:00:00+00',
  'incident_date': '5/1/2023 6:58:00 PM',
  'speed': 'Y',
  'light_condition': 'Daylight',
  'weather': 'Raining',
  'road_condition': 'Wet',
  'address': 'SW ADMIRAL WAY BETWEEN ADMIRAL AVALON RP AND SW ADMIRAL WY OFF RP',
  'location_type': 'Block',
  'lon': -122.371755287,
  'lat': 47.5717276930001,
  'pedestrian_cycle_count': 0,
  'injuries': 0,
  'pedestrian_count': 0,
  'vehicle_count': 1,
  'severity': 'Property Damage Only Collision',
  'source': 'Police Traffic Collision Report',
  'collision_type': 'Other',
  'junction_type': 'Mid-Block (not related to intersection)',
  'report_number': '3904353'},
 {'fatalities': 0,
  'serious_injuries': 0,
  'added_date': '2023/06/04 00:00:00+00',
  'modified_date': '2023/10/30 00:00:00+00',
  'incident_date': '5/1/2023 6:58:00 PM',
  'speed': 'Y',
  'light_condition': 'Daylight',
  'weather': 'Raining',
  'road_condition': 'Wet',
  'address': 'SW ADMIRAL WAY BETWEEN ADMIRAL AVALON RP AND SW ADMIRAL WY OFF RP',
  'location_type': 'Block',
  'lon': -122.371755287,
  'lat': 47.5717276930001,
  'pedestrian_cycle_count': 0,
  'injuries': 0,
  'pedestrian_count': 0,
  'vehicle_count': 1,
  'severity': 'Property Damage Only Collision',
  'source': 'Police Traffic Collision Report',
  'collision_type': 'Other',
  'junction_type': 'Mid-Block (not related to intersection)',
  'report_number': '3904353'},
 {'fatalities': 0,
  'serious_injuries': 0,
  'added_date': '2023/06/04 00:00:00+00',
  'modified_date': '2023/10/30 00:00:00+00',
  'incident_date': '5/1/2023 6:58:00 PM',
  'speed': 'Y',
  'light_condition': 'Daylight',
  'weather': 'Raining',
  'road_condition': 'Wet',
  'address': 'SW ADMIRAL WAY BETWEEN ADMIRAL AVALON RP AND SW ADMIRAL WY OFF RP',
  'location_type': 'Block',
  'lon': -122.371755287,
  'lat': 47.5717276930001,
  'pedestrian_cycle_count': 0,
  'injuries': 0,
  'pedestrian_count': 0,
  'vehicle_count': 1,
  'severity': 'Property Damage Only Collision',
  'source': 'Police Traffic Collision Report',
  'collision_type': 'Other',
  'junction_type': 'Mid-Block (not related to intersection)',
  'report_number': '3904353'},
 {'fatalities': 0,
  'serious_injuries': 0,
  'added_date': '2023/06/04 00:00:00+00',
  'modified_date': '2023/10/30 00:00:00+00',
  'incident_date': '5/1/2023 6:58:00 PM',
  'speed': 'Y',
  'light_condition': 'Daylight',
  'weather': 'Raining',
  'road_condition': 'Wet',
  'address': 'SW ADMIRAL WAY BETWEEN ADMIRAL AVALON RP AND SW ADMIRAL WY OFF RP',
  'location_type': 'Block',
  'lon': -122.371755287,
  'lat': 47.5717276930001,
  'pedestrian_cycle_count': 0,
  'injuries': 0,
  'pedestrian_count': 0,
  'vehicle_count': 1,
  'severity': 'Property Damage Only Collision',
  'source': 'Police Traffic Collision Report',
  'collision_type': 'Other',
  'junction_type': 'Mid-Block (not related to intersection)',
  'report_number': '3904353'}]

@app.route('/')
def hello_world():
    return 'Hello, World!'


@app.route('/add')
def loading():

    # start = Load([],Collision, Vehicle, Location, Date, db, {'d': 'some data'})
    start = Load([Collision, Vehicle, Location, Date], db, j)
    # print('started', start)
    start.load_data()
    print('add route')

    return 'Done loading'






    